apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose
  labels:
    name: menu
spec:
  replicas: 1
  selector:
    matchLabels:
      name: menu
  template:
    metadata:
      labels:
        name: menu
    spec:
      containers:
        - name: compose
          image: kontinu/nginx-menu:v1.0
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: menu
spec:
  selector:
    name: menu
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
