apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
    - name: db
      image: mysql
      ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
    - name: whoami
      image: jwilder/whoami
      ports:
        - name: whoami
          containerPort: 8000
          protocol: TCP
