apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    name: back
spec:
  selector:
    matchLabels:
      name: back
  template:
    metadata:
      labels:
        name: back
    spec:
      containers:
        - name: back
          image: kontinu/go-expert:v1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: back
spec:
  selector:
    name: back
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
