apiVersion: apps/v1
kind: Deployment
metadata:
  name: middle
  labels:
    name: middle
spec:
  selector:
    matchLabels:
      name: middle
  template:
    metadata:
      labels:
        name: middle
    spec:
      containers:
        - name: middle
          image: kontinu/nodejs-expert:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: NEXT_URL
              value: http://back/api

---
apiVersion: v1
kind: Service
metadata:
  name: middle
spec:
  selector:
    name: middle
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
